# Generated by Django 4.0.6 on 2022-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
