# Generated by Django 4.0.6 on 2022-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_remove_customer_otp_remove_customer_phone_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
