# Generated by Django 4.0.6 on 2022-09-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_otp_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=5),
        ),
    ]
