# Generated by Django 4.0.6 on 2022-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0009_alter_phone_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
