# Generated by Django 4.0.6 on 2022-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0010_purchased_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.AddField(
            model_name='phone',
            name='imgurl',
            field=models.CharField(default='', max_length=1000000000000000),
        ),
    ]
