# Generated by Django 4.0.6 on 2022-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0012_purchased_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='Device_storage',
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name='phone',
            name='OS',
            field=models.CharField(default='Andeoid', max_length=10),
        ),
        migrations.AddField(
            model_name='phone',
            name='RAM',
            field=models.IntegerField(default=4),
        ),
    ]
