# Generated by Django 4.0.6 on 2022-09-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0014_color_alter_phone_os'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
