# Generated by Django 4.0.6 on 2022-09-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='customer',
            name='verify_phone_no',
            field=models.BooleanField(default=False),
        ),
    ]
