# Generated by Django 4.0.6 on 2022-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0007_alter_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.CharField(default='?', max_length=15),
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(default='?', max_length=18),
        ),
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default='?', max_length=15),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='?', max_length=5),
        ),
    ]
