# Generated by Django 4.0.6 on 2022-09-05 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0011_remove_phone_image_phone_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_item',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
